<b>Task:</b> Recommend item to the given customer id for a given date.

<b>User Story:</b> User should be able to provide a Customer ID and Date, and program should be able to
recommend item to be purchased.

<b>Hint:</b> Approach would be given importance over result

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Dataset for Task 1,2,3/Online Retail.xlsx")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

### 1. Perform EDA

In [4]:
print(f"The shape of the data: {df.shape}")

The shape of the data: (541909, 8)

In [5]:
print(f"No.of Customers: {len(df['CustomerID'].unique())} " )
print(f"No.of Items: {len(df['StockCode'].unique())}")
print(f"No.of Countries: {len(df['Country'].unique())}")

No.of Customers: 4373
No.of Items: 4070
No.of Countries: 38

In [6]:
# Information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

Here, we can observe that we have <b>1,35,080</b> missing values in <b>CustomerID</b>    column. So, we should remove those missing  values by using <i>dropna()</i> function

In [7]:
# Remove missing values and convert the type of CustomerID column from 
# float to int
df['CustomerID'] = df['CustomerID'].dropna()
df["CustomerID"] = df["CustomerID"].astype("Int64")
print(f"Type of CustomerID column: {df['CustomerID'].dtype}")

Type of CustomerID column: Int64

In [8]:
# Separate date from InvoiceDate
df['date'] = df['InvoiceDate'].dt.date

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2010-12-01
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,2010-12-01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01

In [9]:
df.shape

(541909, 9)

In [10]:
df['CustomerID'].value_counts().describe()

count    4372.000000
mean       93.053294
std       232.471608
min         1.000000
25%        17.000000
50%        42.000000
75%       102.000000
max      7983.000000
Name: CustomerID, dtype: float64

In [11]:
x = df['CustomerID'].value_counts() > 100

In [12]:
x[x].shape

(1108,)

In [13]:
y= x[x].index
y

Index([17841, 14911, 14096, 12748, 14606, 15311, 14646, 13089, 13263, 14298,
       ...
       13271, 16023, 17061, 13849, 15105, 16960, 14515, 16885, 16892, 15113],
      dtype='Int64', length=1108)

In [14]:
df = df[df['CustomerID'].isin(y)]
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2010-12-01
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,2010-12-01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,2010-12-01

In [15]:
df.shape

(295618, 9)

In [16]:
number_items = df.groupby('Description')['Quantity'].sum().reset_index()

In [17]:
len(df['Description'].unique())

3782

In [18]:
number_items.head()

                      Description  Quantity
0   4 PURPLE FLOCK DINNER CANDLES       103
1   50'S CHRISTMAS GIFT BAG LARGE      1355
2               DOLLY GIRL BEAKER      2236
3     I LOVE LONDON MINI BACKPACK       278
4     I LOVE LONDON MINI RUCKSACK         1

In [19]:
number_items.shape

(3782, 2)

In [20]:
number_items.rename(columns={'Quantity':'total_quantity'},inplace=True)

In [21]:
number_items.head()

                      Description  total_quantity
0   4 PURPLE FLOCK DINNER CANDLES             103
1   50'S CHRISTMAS GIFT BAG LARGE            1355
2               DOLLY GIRL BEAKER            2236
3     I LOVE LONDON MINI BACKPACK             278
4     I LOVE LONDON MINI RUCKSACK               1

In [22]:
final_df = df.merge(number_items, on = 'Description')

In [23]:
final_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,total_quantity
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2010-12-01,24447
1,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:02:00,2.55,17850,United Kingdom,2010-12-01,24447
2,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:32:00,2.55,17850,United Kingdom,2010-12-01,24447
3,536390,85123A,WHITE HANGING HEART T-LIGHT HOLDER,64,2010-12-01 10:19:00,2.55,17511,United Kingdom,2010-12-01,24447
4,536394,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 10:39:00,2.55,13408,United Kingdom,2010-12-01,24447

In [24]:
final_df['total_quantity'].describe()

count    295618.000000
mean       3225.723146
std        4381.949497
min       -3228.000000
25%         672.000000
50%        1641.000000
75%        4149.000000
max       33501.000000
Name: total_quantity, dtype: float64

In [25]:
# Lets take those books which got at least 1000 quantity of items
final_df = final_df[final_df['total_quantity'] > 1000]

In [26]:
final_df.shape

(194464, 10)

In [27]:
# lets drop the duplicates
final_df.drop_duplicates(['CustomerID','Description'],inplace=True)

In [28]:
final_df.shape

(103961, 10)

In [29]:
# let's create a pivot table
item_pivot = final_df.pivot_table(columns = 'CustomerID',index = 'Description',values = 'Quantity')

In [30]:
item_pivot

CustomerID,12347,12357,12359,12360,12362,12370,12378,12380,12395,12397,...,18226,18229,18231,18235,18241,18245,18257,18260,18272,18283
Description,,,,,,,,,,,,,,,,,,,,,
50'S CHRISTMAS GIFT BAG LARGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOLLY GIRL BEAKER,NaN,NaN,12.0,NaN,12.0,NaN,NaN,NaN,12.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RED SPOT GIFT BAG LARGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,1.0
SET 2 TEA TOWELS I LOVE LONDON,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 COLOUR SPACEBOY PEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YOU'RE CONFUSING ME METAL SIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
ZINC FOLKART SLEIGH BELLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
ZINC METAL HEART DECORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZINC T-LIGHT HOLDER STARS SMALL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZINC WILLIE WINKIE CANDLE STICK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
item_pivot.shape

(892, 1108)

In [32]:
item_pivot.fillna(0,inplace = True)

In [33]:
item_pivot

CustomerID,12347,12357,12359,12360,12362,12370,12378,12380,12395,12397,...,18226,18229,18231,18235,18241,18245,18257,18260,18272,18283
Description,,,,,,,,,,,,,,,,,,,,,
50'S CHRISTMAS GIFT BAG LARGE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DOLLY GIRL BEAKER,0.0,0.0,12.0,0.0,12.0,0.0,0.0,0.0,12.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RED SPOT GIFT BAG LARGE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0
SET 2 TEA TOWELS I LOVE LONDON,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 COLOUR SPACEBOY PEN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YOU'RE CONFUSING ME METAL SIGN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
ZINC FOLKART SLEIGH BELLS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
ZINC METAL HEART DECORATION,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZINC T-LIGHT HOLDER STARS SMALL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZINC WILLIE WINKIE CANDLE STICK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Training model

In [34]:
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [35]:
item_sparse = csr_matrix(item_pivot)

In [36]:
type(item_sparse)

scipy.sparse._csr.csr_matrix

In [37]:
model = NearestNeighbors(algorithm= 'brute')
model.fit(item_sparse)

NearestNeighbors(algorithm='brute')

In [38]:
item_pivot.iloc[:]

CustomerID,12347,12357,12359,12360,12362,12370,12378,12380,12395,12397,...,18226,18229,18231,18235,18241,18245,18257,18260,18272,18283
Description,,,,,,,,,,,,,,,,,,,,,
50'S CHRISTMAS GIFT BAG LARGE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DOLLY GIRL BEAKER,0.0,0.0,12.0,0.0,12.0,0.0,0.0,0.0,12.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RED SPOT GIFT BAG LARGE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,1.0
SET 2 TEA TOWELS I LOVE LONDON,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 COLOUR SPACEBOY PEN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YOU'RE CONFUSING ME METAL SIGN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
ZINC FOLKART SLEIGH BELLS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
ZINC METAL HEART DECORATION,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZINC T-LIGHT HOLDER STARS SMALL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZINC WILLIE WINKIE CANDLE STICK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
item_pivot.shape

(892, 1108)

In [40]:
distance, suggestion = model.kneighbors(item_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors=6 )

In [41]:
distance

array([[  0.        , 163.79255172, 210.80085389, 214.87205495,
        231.82752209, 238.64618162]])

In [42]:
suggestion

array([[237, 242, 584, 528, 228, 241]], dtype=int64)

In [43]:
item_pivot.iloc[237,:]

CustomerID
12347     0.0
12357     0.0
12359     0.0
12360     0.0
12362     0.0
         ...
18245     0.0
18257     0.0
18260    12.0
18272     0.0
18283     1.0
Name: FELTCRAFT BUTTERFLY HEARTS, Length: 1108, dtype: float64

In [44]:
for i in range(len(suggestion)):
    print(item_pivot.index[suggestion[i]])

Index(['FELTCRAFT BUTTERFLY HEARTS', 'FELTCRAFT DOLL MOLLY',
       'RED FLORAL FELTCRAFT SHOULDER BAG', 'PHOTO CUBE',
       'FAIRY TALE COTTAGE NIGHTLIGHT', 'FELTCRAFT CUSHION RABBIT'],
      dtype='object', name='Description')

In [45]:
import numpy as np

In [46]:
def recommend_item(item_name, no_of_recommends = 6):
    item_id = np.where(item_pivot.index == item_name)[0][0]
    distance,suggestion = model.kneighbors(item_pivot.iloc[item_id,:].values.reshape(1,-1),
                                           n_neighbors = no_of_recommends)
    
    for i in range(len(suggestion)):
        items = item_pivot.index[suggestion[i]]
        for j in items:
            if j== item_name:
                print(f"You searched {item_name}\n")
                print("The suggestion items are:\n")
            else:
                print(j)

In [47]:
item_name = "FELTCRAFT BUTTERFLY HEARTS"
recommend_item(item_name,8)

You searched FELTCRAFT BUTTERFLY HEARTS

The suggestion items are:

FELTCRAFT DOLL MOLLY
RED FLORAL FELTCRAFT SHOULDER BAG
PHOTO CUBE
FAIRY TALE COTTAGE NIGHTLIGHT
FELTCRAFT CUSHION RABBIT
FELTCRAFT CUSHION BUTTERFLY
FELTCRAFT CUSHION OWL